// Package netprobe 对应原脚本第 546~787 行：从一份候选域名列表里，挑一个
// 延迟最低、支持 TLS1.3、且证书不太大的域名，用作 Reality 的伪装 SNI。
package netprobe

// Candidates 是候选域名列表，跟原脚本 HANDSHAKE_CANDIDATES 逐条一致
// （用脚本直接抽取生成，没有手工转录，顺序也原样保留——顺序其实不影响
// 最终选出哪个域名，见 select.go 里 Select() 的算法说明）。
var Candidates = []string{
	"prod.us-east-1.ui.gcr-chat.marketing.aws.dev",
	"img-prod-cms-rt-microsoft-com.akamaized.net",
	"gray-config-prod.api.cdn.arcpublishing.com",
	"gray.video-player.arcpublishing.com",
	"res.public.onecdn.static.microsoft",
	"downloaddispatch.itunes.apple.com",
	"i7158c100-ds-aksb-a.akamaihd.net",
	"gray-config-prod.api.arc-cdn.net",
	"ms-python.gallerycdn.vsassets.io",
	"ms-vscode.gallerycdn.vsassets.io",
	"location-services-prd.tesla.com",
	"vscjava.gallerycdn.vsassets.io",
	"d3agakyjgjv5i8.cloudfront.net",
	"a.b.cdn.console.awsstatic.com",
	"prod.pa.cdn.uis.awsstatic.com",
	"github.gallerycdn.vsassets.io",
	"cdn-dynmedia-1.microsoft.com",
	"store-images.s-microsoft.com",
	"amp-api-edge.apps.apple.com",
	"prod.log.shortbread.aws.dev",
	"visualstudio.microsoft.com",
	"gray-wowt-prod.gtv-cdn.com",
	"configuration.ls.apple.com",
	"services.digitaleast.mobi",
	"tag-logger.demandbase.com",
	"www.google-analytics.com",
	"publisher.liveperson.net",
	"se-edge.itunes.apple.com",
	"iosapps.itunes.apple.com",
	"downloadmirror.intel.com",
	"d.impactradius-event.com",
	"digitalassets.tesla.com",
	"fpinit.itunes.apple.com",
	"s7mbrstream.scene7.com",
	"devblogs.microsoft.com",
	"api.company-target.com",
	"static.cloud.coveo.com",
	"ds-aksb-a.akamaihd.net",
	"assets-xbxweb.xbox.com",
	"cua-chat-ui.tesla.com",
	"cdn77.api.userway.org",
	"s.company-target.com",
	"munchkin.marketo.net",
	"gsp-ssl.ls.apple.com",
	"consent.trustarc.com",
	"catalog.gamepass.com",
	"cdnssl.clicktale.net",
	"acctcdn.msftauth.net",
	"intelcorp.scene7.com",
	"electronics.sony.com",
	"is1-ssl.mzstatic.com",
	"res-1.cdn.office.net",
	"lpcdn.lpsnmedia.net",
	"assets.adobedtm.com",
	"d.oracleinfinity.io",
	"aadcdn.msftauth.net",
	"azure.microsoft.com",
	"logx.optimizely.com",
	"assets-www.xbox.com",
	"tag.demandbase.com",
	"ts2.tc.mm.bing.net",
	"t0.m.awsstatic.com",
	"polyfill-fastly.io",
	"d0.m.awsstatic.com",
	"ce.mf.marsflag.com",
	"ts1.tc.mm.bing.net",
	"d2c.aws.amazon.com",
	"ts3.tc.mm.bing.net",
	"ts4.tc.mm.bing.net",
	"beacon.gtv-pub.com",
	"statici.icloud.com",
	"c.s-microsoft.com",
	"vs.aws.amazon.com",
	"images.nvidia.com",
	"s.mp.marsflag.com",
	"www.microsoft.com",
	"sisu.xboxlive.com",
	"apps.mzstatic.com",
	"go.microsoft.com",
	"a0.awsstatic.com",
	"mscom.demdex.net",
	"s0.awsstatic.com",
	"d1.awsstatic.com",
	"download.amd.com",
	"cdn.userway.org",
	"ocsp2.apple.com",
	"cdn.bizible.com",
	"tags.tiqcdn.com",
	"s.go-mpulse.net",
	"cdn.bizibly.com",
	"drivers.amd.com",
	"aws.amazon.com",
	"snap.licdn.com",
	"www.nvidia.com",
	"c.marsflag.com",
	"apps.apple.com",
	"www.icloud.com",
	"www.oracle.com",
	"www.xilinx.com",
	"www.tesla.com",
	"www.intel.com",
	"www.apple.com",
	"www.wowt.com",
	"xp.apple.com",
	"www.bing.com",
	"rum.hlx.page",
	"www.sony.com",
	"www.xbox.com",
	"ipv6.6sc.co",
	"www.aws.com",
	"www.amd.com",
	"th.bing.com",
	"r.bing.com",
	"intel.com",
	"b.6sc.co",
	"j.6sc.co",
	"c.6sc.co",
	"aws.com",
	"amd.com",
}

// FallbackDomain 对应原脚本："警告：未找到支持TLS1.3的域名，使用
// gateway.icloud.com 作为默认值"。
const FallbackDomain = "gateway.icloud.com"

// maxCertDER 对应原脚本注释：Reality 硬限约 8192 字节，这里用叶证书的 DER
// 体积做启发式判断，超过就跳过（含大 OCSP/长证书链风险）。
const maxCertDER = 5500
